### ISSUE TITLE
Q: why `Alien-Libxml2` module is perl arch?

### ISSUE THREAD

**Issue by kloczek** [PerlAlien/Alien-Libxml2#35]
Looks like `Alien-Libxml2` module do not install any DSOs and despite that it isnstalls all files in perl arch instead perl lib tree.
Is thet intentional/correct? 🤔

**Comment by plicease** [comment]
If you do a `share` install it will install architecture dependent libraries in the share directory:

```
% ls blib/lib/auto/share/dist/Alien-Libxml2/lib 
cmake/  libxml2.a  libxml2.la*  pkgconfig/
```

Installs with these files should not be shared with other architectures.  They could in theory be shared with Perls of the same underlying architecture but different build options, for example  threaded and threaded Perls could use the same `libxml2.a`, but Perl doesn't have a search path that corresponds with that.

For a `system` install these files won't be installed so in theory installing into the arch search path is unnecessary, but if these `Alien::Libxml2` gets upgraded, then you might end up with installs in both locations (if using a standard CPAN client like `cpanm`), or you end up with architecture dependent directories in the `lib` share directory (if upgrading in place via `App::af`), the former will probably break the alien the latter is a more subtle bug that is only a problem if the lib directory is shared.

It's more less impossible for the `Alien::Build` core to know ahead of time (or indeed even after for a `system` install) if the particular `Alien` produces architectural dependent files.  An Alien that alienizes a JavaScript library, for example  should not be installed in the arch directory.  However, the vast majority of Aliens DO produce architectural specific files, so we make that the default, and there is an `Alien::Build` meta property `arch` which can be used to turn this behavior off.

https://metacpan.org/pod/Alien::Build#arch
