### ISSUE TITLE
Failed install macOS Monterey: Failed test 'xs'

### ISSUE THREAD

**Issue by louellette** [PerlAlien/Alien-Libxml2#36]
Thanks in advance for your help. I am trying to install XML::LibXML and I fail in the tests in Alien-Libxml2. Failed test 'xs': t/alien_libxml2.t line 27

Can't load '/Users/lisaouellette/.cpanm/work/1664925537.59745/Alien-Libxml2-0.19/_alien/tmp/test-alien-n_AXmg/auto/Libxml2/Libxml2.bundle' for module Libxml2: dlopen(/Users/lisaouellette/.cpanm/work/1664925537.59745/Alien-Libxml2-0.19/_alien/tmp/test-alien-n_AXmg/auto/Libxml2/Libxml2.bundle, 0x0002): symbol not found in flat namespace (_xmlCleanupParser) at /Users/lisaouellette/perl5/perlbrew/perls/perl-5.22.1/lib/5.22.1/darwin-2level/DynaLoader.pm line 197.
[build.log](https://github.com/PerlAlien/Alien-Libxml2/files/9715197/build.log)

Build log is attached.

**Comment by plicease** [comment]
I can't tell from just the log, but did you build libxml2 with the same compiler (or possibly is one C++ and the ther build as C)?  I assume that you built it yourself since it is installed in `~/opt`.  I know that it works with the libxml2 provided by both MacBrew and MacPorts, because we test against the MacBrew version in CI and I use MacPorts on my ARM64 Macs.

**Comment by louellette** [comment]
I'm using the libxml2 from anaconda, so no I didn't compile it. I can try to use the MacPorts one. Can you direct me on now to do that?

**Comment by plicease** [comment]
1. Install MacPorts if you do not already have it https://www.macports.org/
 2. `sudo port install libxml2`

If you have PKG_CONFIG_PATH set to find anaconda, you will want to update it to point to the macports version (`xml2-config --libs` should give you a hint, the default install location for macports is `/opt/local`)

You can also let `Alien::Libxml2` build and install libxml2 as well, if you set `ALIEN_INSTALL_TYPE=share`, this would be the default behavior if it hadn't found the anaconda install.

**Comment by louellette** [comment]
Thank you for your help. This worked perfectly.
