### ISSUE TITLE
cpan Alien:Libxml2 Failed.

### ISSUE THREAD

**Issue by HGGshiwo** [PerlAlien/Alien-Libxml2#41]
I try to install Alien:Libxml2 by the following command:
```
cpan Alien:Libxml2
```
however, it is failed, the log is:
```
# Failed test 'xs'
# at t/alien_libxml2.t line 27.
#   XSLoader failed
#     Can't load '/home/bingwenzhang/.cpan/build/Alien-Libxml2-0.19-_wUUo0/_alien/tmp/test-alien-dF8GfY/auto/Libxml2/Libxml2.so' for module Libxml2: libicui18n.so.58: cannot open shared object file: No such file or directory at /usr/lib/x86_64-linux-gnu/perl/5.24/DynaLoader.pm line 187.
#  at /home/bingwenzhang/perl-modules/share/perl/5.24.1/Test/Alien.pm line 483.
# Compilation failed in require at /home/bingwenzhang/perl-modules/share/perl/5.24.1/Test/Alien.pm line 483.
# BEGIN failed--compilation aborted at /home/bingwenzhang/perl-modules/share/perl/5.24.1/Test/Alien.pm line 483.
t/alien_libxml2.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 

Test Summary Report
-------------------
t/alien_libxml2.t (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=2, Tests=4,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.66 cusr  0.07 csys =  0.76 CPU)
Result: FAIL
Failed 1/2 test programs. 1/4 subtests failed.
Makefile:876: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 1
  PLICEASE/Alien-Libxml2-0.19.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports PLICEASE/Alien-Libxml2-0.19.tar.gz
```

**Comment by plicease** [comment]
Usually this diagnostic:  `libicui18n.so.58: cannot open shared object file: No such file or directory` means that the compiler was able to link against the library, but was not able to find it at run time for the test.  Can you try running ldd on `/home/bingwenzhang/.cpan/build/Alien-Libxml2-0.19-_wUUo0/_alien/tmp/test-alien-dF8GfY/auto/Libxml2/Libxml2.so` to see if it is also having trouble finding the library?

I'm assuming Linux because the dynamic library is a .so, but if you could please provide the full test output which will include system information that is helpful in diagnosing problems.

**Comment by HGGshiwo** [comment]
Thanks for your quick reply, that is the output of ldd:
```
ldd /home/bingwenzhang/.cpan/build/Alien-Libxml2-0.19-_wUUo0/_alien/tmp/test-alien-dF8GfY/auto/Libxml2/Libxml2.so
        linux-vdso.so.1 (0x00007ffd197c8000)
        libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f9cf45b5000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9cf439b000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f9cf4175000)
        libicui18n.so.58 => not found
        libicuuc.so.58 => not found
        libicudata.so.58 => not found
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9cf402f000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9cf4029000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9cf3e55000)
        libicui18n.so.57 => /usr/lib/x86_64-linux-gnu/libicui18n.so.57 (0x00007f9cf39da000)
        libicuuc.so.57 => /usr/lib/x86_64-linux-gnu/libicuuc.so.57 (0x00007f9cf3632000)
        libicudata.so.57 => /usr/lib/x86_64-linux-gnu/libicudata.so.57 (0x00007f9cf1bb5000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9cf1b91000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9cf4b8f000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9cf19c4000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9cf19aa000)
```

How can I install the missing .so file?

**Comment by plicease** [comment]
> How can I install the missing .so file?

You probably just need to install the appropriate packages, but how you do that depends on the distribution you are using.  On Debian/Ubunu based systems you can search the content of packages [here](https://www.debian.org/distrib/packages) or [here](https://packages.ubuntu.com/).  However, I don't see `.58` versions for recent versions of either Debian or Ubuntu.  If you have an older Debian derivative I think the package might be called libicu58?  I am not as familiar with other distributions.

**Comment by plicease** [comment]
btw- another alternative is to install Alien::Libxml2 in `share` mode, which builds the libxml2 from source.  It won't include the libicu features unless they are installed, but depending on your needs may be good enough.  To do this install with the `ALIEN_INSTALL_TYPE` environment variable set to `share`:

```
% env ALIEN_INSTALL_TYPE=share cpanm Alien::Libxml2
```

**Comment by HGGshiwo** [comment]
Thanks for your reply, I finally copied some missing libs from the anaconda library and it works
